plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'

	id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.asdf'
version = '0.0.1-dev'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'mysql:mysql-connector-java:8.0.32'

	// Spring Security와 JWT 의존성 추가
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// JWT 라이브러리 추가
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'

	compileOnly 'org.projectlombok:lombok'

	annotationProcessor 'org.projectlombok:lombok'

	// JUnit 5를 이용한 테스트를 위한 의존성
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// 임시 MySQL 컨테이너 생성하여 유닛테스트를 위한 의존성
	testImplementation 'org.testcontainers:junit-jupiter:1.20.1'
	testImplementation 'org.testcontainers:testcontainers:1.20.1'
	testImplementation 'org.testcontainers:mysql:1.20.1'

	//Spring Security 테스트를 위한 의존성 추가
	testImplementation 'org.springframework.security:spring-security-test'

	//JUnit 5 테스트를 위한 런타임 의존성 추가
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//JWT 라이브러리 구현체를 추가
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

tasks.named('test') {
	useJUnitPlatform()

	testLogging{
		// 테스트 이벤트 중 어떤 것을 로그로 출력할지 설정
		events "passed", "skipped", "failed"
		// 테스트 케이스 별 결과를 항상 출력
		outputs.upToDateWhen {false}
		// Java Agent 경고 메세지 억제
		jvmArgs '-XX:+EnableDynamicAgentLoading'
	}
}

spotless{
	java{
		googleJavaFormat('1.22.0').reflowLongStrings()
	}
}

build.dependsOn 'spotlessApply'

bootRun {
	String activeProfile = System.properties['spring.profiles.active']
	systemProperty 'spring.profiles.active', activeProfile
}